### ISSUE TITLE
Support for NodeJS 10.15.3 LTS?

### ISSUE THREAD

**Issue by politician** [mhart/aws4fetch#3]
I'm running NodeJS 10.7.0, but it looks like [util.TextEncoder](https://nodejs.org/dist/latest-v10.x/docs/api/util.html#util_class_util_textencoder) should exist in this version.  Any ideas what I'm doing wrong here?

```
/snip/node_modules/aws4fetch/dist/aws4fetch.cjs.js:5
const encoder = new TextEncoder('utf-8');
                ^

ReferenceError: TextEncoder is not defined
    at Object.<anonymous> (/snip/node_modules/aws4fetch/dist/aws4fetch.cjs.js:5:17)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/snip/my_code.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
```

**Comment by mhart** [comment]
This is not supported on any Node.js version right now – as the README says: `for environments that support fetch and SubtleCrypto – that is, modern web browsers and JS platforms like Cloudflare Workers`

You probably want https://github.com/mhart/aws4

**Comment by aleclarson** [comment]
You can use my fork if you need NodeJS support:
https://github.com/aleclarson/aws4fetch/tree/nodejs

**Comment by rafaelnogueira1** [comment]
> You can use my fork if you need NodeJS support:
> https://github.com/aleclarson/aws4fetch/tree/nodejs

Wouldn't it be a good idea to open a PR with this modification?

**Comment by mhart** [comment]
I'd be interested to know the use case given https://github.com/mhart/aws4

**Comment by aleclarson** [comment]
> Wouldn't it be a good idea to open a PR with this modification?

Feel free to do so.

> I'd be interested to know the use case given [mhart/aws4](https://github.com/mhart/aws4)

I prefer the `fetch` API.

**Comment by rafaelnogueira1** [comment]
I dig a little more and the new versions of nodejs already fix this problem.
