### ISSUE TITLE
 crypto is not defined

### ISSUE THREAD

**Issue by its-dibo** [mhart/aws4fetch#61]
I got this error
```
 ReferenceError: crypto is not defined
0|mobarmegeen-backend  |     at hmac (node_modules/aws4fetch/dist/aws4fetch.cjs.js:223:21)
0|mobarmegeen-backend  |     at AwsV4Signer.signature (node_modules/aws4fetch/dist/aws4fetch.cjs.js:185:27)
0|mobarmegeen-backend  |     at AwsV4Signer.authHeader (node_modules/aws4fetch/dist/aws4fetch.cjs.js:177:34)
0|mobarmegeen-backend  |     at AwsV4Signer.sign (node_modules/aws4fetch/dist/aws4fetch.cjs.js:164:52)
0|mobarmegeen-backend  |     at AwsClient.sign (node_modules/aws4fetch/dist/aws4fetch.cjs.js:56:57)
0|mobarmegeen-backend  |     at AwsClient.fetch (node_modules/aws4fetch/dist/aws4fetch.cjs.js:69:40)
0|mobarmegeen-backend  |     at FilesCloudflareService.save (/apps/src/api/files/fs-providers/files.cloudflare.service.ts:54:8)
0|mobarmegeen-backend  |     at /apps/src/api/posts/posts.service.ts:135:10
0|mobarmegeen-backend  |     at matcher (/apps/src/api/files/files.utils.ts:47:14)
0|mobarmegeen-backend  |     at replaceAsync (/apps/src/api/files/files.utils.ts:90:9)
0|mobarmegeen-backend  |     at extractInlineData (/apps/src/api/files/files.utils.ts:52:7)
0|mobarmegeen-backend  |     at PostsService.saveFiles (/apps/src/api/posts/posts.service.ts:121:29)
0|mobarmegeen-backend  |     at PostsService.updateById (/apps/src/api/posts/posts.service.ts:45:17)
0|mobarmegeen-backend  |     at PostsController.update (/apps/src/api/posts/posts.controller.ts:104:25)
0|mobarmegeen-backend  |     at node_modules/@nestjs/core/router/router-execution-context.js:38:29
0|mobarmegeen-backend  |     at processTicksAndRejections (node:internal/process/task_queues:95:5)
0|mobarmegeen-backend  |     at async node_modules/@nestjs/core/router/router-execution-context.js:46:28
0|mobarmegeen-backend  |     at async Object.<anonymous> (node_modules/@nestjs/core/router/router-proxy.js:9:17)
```

the code:
```
let client = new AwsClient({
      accessKeyId: ***,
      secretAccessKey: ***!,
    });

let baseUrl =  `https://${accountId}.r2.cloudflarestorage.com`

client
      .fetch(`${baseUrl}/file.txt`, {
        method: 'put',
        body: 'test',
      })

```

I don't use `crypto` anywhere in my code
even installing crypto doesn't help `npm i crypto`

**Comment by mhart** [comment]
Where are you running this? As the README says, this is "for environments that support fetch and SubtleCrypto"

**Comment by its-dibo** [comment]
> AwsClient

in a Nodejs app which supports `fetch`

**Comment by mhart** [comment]
Which Node.js version? Which OS?

**Comment by its-dibo** [comment]
> Which Node.js version? Which OS?

Node v20
OS: ubuntu 22

**Comment by mhart** [comment]
Not sure what's wrong with your env – it's defined for me:
```
$ node
Welcome to Node.js v20.11.0.
Type ".help" for more information.
> typeof crypto
'object'
```

**Comment by sino1641** [comment]
HI 
I tried adding `const crypto = require('crypto');` to the top of the code then it works.
I am day1 on nodejs using fedora with node output:
```bash
$ node
Welcome to Node.js v18.18.2.
Type ".help" for more information.
> typeof crypto
'object'
```
May it wouldbe of help.

**Comment by its-dibo** [comment]
> I tried adding `const crypto = require('crypto');`

this wo'nt work here because aws4fetch is an external package and we cannot modify its code base

**Comment by zdmc23** [comment]
@its-dibo , try adding the Vercel Edge Runtime Polyfill (https://edge-runtime.vercel.app/packages/ponyfill) package:

```bash
pnpm add @edge-runtime/ponyfill
```

then to use it:

```js
import { crypto } from '@edge-runtime/ponyfill'
```

**Comment by luizzappa** [comment]
In case anyone is having this problem running `Nuxt` locally, you can create a plugin as follows:

```javascript
export default defineNuxtPlugin(() => {
  const config = useRuntimeConfig();

  if (process.server && config.public.env.toLocaleLowerCase() !== 'prod') {
    const crypto = require('crypto');
    global.crypto = crypto;
  }
})
```

**Comment by 1rwilson** [comment]
> I tried adding `const crypto = require('crypto');`

I am experiencing the same issue on both my local node.js environment and also when deploying on google cloud functions:
<img width="892" alt="Screenshot 2024-09-05 at 20 08 44" src="https://github.com/user-attachments/assets/c9ca7446-86be-4733-b30f-32e7b7a85a1e">

Simply adding const crypto = require('crypto'); to the beginning of aws4fetch.cjs.js fixes the problem on my local environment. But I can't do this when deploying to GCF. Could this one line be added as per aws4.js ?

**Comment by duinness** [comment]
I hit this error while using vercel ai sdk and tracked the error to aws4fetch.
I resolved the issue by moving my service from Node 18 to Node 20.17.0

**Comment by mhart** [comment]
Yeah, as the README says, this project is for modern JS environments. The
https://github.com/mhart/aws4 project supports all Node.js environments.

**Comment by theashggl** [comment]
Using better auth I got the same issue when signing up. Fixed it by importing the package as suggested by ai.
```js
import crypto from "node:crypto";

globalThis.crypto = crypto.webcrypto;

import express from "express";
import { betterAuth } from "better-auth";
```
